version: 2.1
jobs:
  lint:
    docker:
      - image: bitnami/python:3.8
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Check lint
          command: |
            make flake8
  unit_test:
    docker:
      - image: pennlabs/tox:d94aa67bd172351b25b8fd33308478be59f608ac
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Unit test
          command: |
            pip install codecov
            make tox
            codecov -t $TOKEN_CODECOV
  deploy_pypi:
    docker:
      - image: bitnami/python:3.8
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Publish on Pypi
          command: |
            make deploy
  deploy_docker:
    environment:
      IMAGE_NAME: mbouamama/myjwt/myjwt
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image prod
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              DOCKER_TAG="latest"
            fi

            if [ -n "${CIRCLE_TAG}" ]; then
              DOCKER_TAG="$CIRCLE_TAG"
            fi
            echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_LOGIN --password-stdin docker.pkg.github.com
            docker build -t docker.pkg.github.com/$IMAGE_NAME:$DOCKER_TAG .
            docker push docker.pkg.github.com/$IMAGE_NAME:$DOCKER_TAG

workflows:
  check_lint:
    jobs:
      - lint
  check_unit_test:
    jobs:
      - unit_test:
          context: myjwt
  deploy:
    jobs:
      - deploy_pypi:
          context: myjwt
          filters:
            branches:
              ignore: /.*/
            tags:
              only: '/[0-9]+(\.[0-9]+)*/'
      - deploy_docker:
          context: myjwt
          filters:
            branches:
              only: master